version: '3.8'

volumes:
  data:

services:
  firefox:
    image: jlesage/firefox:latest
    restart: always
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - VNC_QUALITY=2
      - VNC_COMPRESSION=9
    volumes:
      - data:/config:rw
    networks:
      - browser-network
    shm_size: 2g

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - firefox
    networks:
      - browser-network

networks:
  browser-network:
    driver: bridge
