version: '3.8'

volumes:
  data:

services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - DISABLE_IPV6=true
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - data:/config:rw
    shm_size: "2gb"
    networks:
      - browser-network
    devices:
      - /dev/dri:/dev/dri
    security_opt:
      - seccomp:unconfined

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - firefox
    networks:
      - browser-network

networks:
  browser-network:
    driver: bridge
